### ISSUE TITLE
Playback of video-only videos not possible on iOS (with only hls enabled)

### ISSUE THREAD

**Issue by tgurr** [Chocobozzz/PeerTube#3001]
**What happened?**

First of all thanks for adressing https://github.com/Chocobozzz/PeerTube/issues/2955 in the previous PeerTube release, it mostly works fine now, however there's an issue left with video-only videos that don't have an audio track, which still don't play on iOS (we've only hls is enabled, if that matters in this case).

**What do you expect to happen instead?**

Playback working as expected.

**Steps to reproduce:**

1. set webtorrent to false, hls to true
2. restart peertube
3. ffmpeg -i video.mp4 -vcodec copy -an video_only.mp4
4. upload the video-only video
5. try to play it on an iOS device

**Additional information**
* PeerTube version or URL: 2.3.0
* Browser name/version: iOS 13.6 / Safari
* NodeJS version: 12.18.2

**Comment by Chocobozzz** [comment]
Thanks for the issue @tgurr. Should be fixed in https://github.com/Chocobozzz/PeerTube/commit/d7b1c7b4f1a9099eac61f944249f2cdb4f94415e

**Comment by tgurr** [comment]
I've just updated our instance to 2.4.0 and can confirm that it works now with video only files. However there's one issue, it appear to only apply to newly uploaded videos, videos already uploaded with e.g. 2.3.0 still do not play. That isn't an issue for us as we only have a few which we can re-upload, but it may be a problem for other people so I just wanted to leave a note here.

**Comment by Chocobozzz** [comment]
@tgurr yes, unfortunately you'll have to reupload your videos or run transcoding jobs using the [CLI](https://docs.joinpeertube.org/#/maintain-tools?id=create-transcoding-jobjs)
