### ISSUE TITLE
Sidebar overlaps content

### ISSUE THREAD

**Issue by emansom** [Chocobozzz/PeerTube#5326]
### Describe the current behavior

From time to time experiencing this when docking a tab to one part of the screen and then to full window again (changing the viewport of the document).

Browser being Firefox on a 1440p display with 1.25x scaling.

See the lack of spacing between the sidebar and the content:

![Schermafdruk van 2022-09-27 08-49-04](https://user-images.githubusercontent.com/981494/192453617-22b64f67-25f7-4c18-bef2-8946b365ac9a.png)

It worsens the less horizontal space is available (this is **before** it transitions to mobile view with the sidebar hidden):

![Schermafdruk van 2022-09-27 08-53-51](https://user-images.githubusercontent.com/981494/192454723-e64f3770-40c7-49f5-b9b8-e6e74c0c8ff4.png)

### Steps to reproduce

1. Setup latest PeerTube somewhere
2. Access it from Firefox on a 1440p screen with some display scaling factor applied (not text scaling)
3. Profit

### Describe the expected behavior

Sidebar not overlapping main content in a desktop/tablet sized viewport

**Comment by Chocobozzz** [comment]
Thanks! It should be fixed by https://github.com/Chocobozzz/PeerTube/commit/20eb313f020ac1a2fab02a377aec457c5a4695f4

**Comment by emansom** [comment]
> Thanks! It should be fixed by [20eb313](https://github.com/Chocobozzz/PeerTube/commit/20eb313f020ac1a2fab02a377aec457c5a4695f4)

Sadly not. 😔 

Experiencing the exact same behavior still, using latest develop branch and cleaned all browser cache beforehand.

**Comment by Chocobozzz** [comment]
It's weird, I cannot reproduce anymore on peertube2.cpy.re
There's only a small responsive bug regarding the channel name, but we now have the margin between the menu and the main content

![Capture d’écran 2022-10-11 à 08 36 15](https://user-images.githubusercontent.com/5180488/195013960-dbd31076-c138-45e3-adb8-c35bc13add7e.png)

**Comment by emansom** [comment]
> It's weird, I cannot reproduce anymore on peertube2.cpy.re There's only a small responsive bug regarding the channel name, but we now have the margin between the menu and the main content

I can still reproduce it on your instance. Using a 27" 1440p display with 1.25x scaling factor on GNOME 43 in Firefox, then modifying the window dimensions with a mouse.

![Schermafdruk van 2022-10-11 22-01-58](https://user-images.githubusercontent.com/981494/195187769-58f5ae02-9cb4-48c1-9e9c-e0ca73bf7152.png)

**Comment by emansom** [comment]
> @emansom Please test on https://peertube2.cpy.re and not https://peertube.cpy.re :) Note that under 800px the menu will be on top/ will hide the main content like we saw in your screenshot

Woops my bad. Probably shouldn't drink six espresso in a day. 😅 

Yes, works perfectly now. 👍🏻

**Comment by emansom** [comment]
Much better with the menu!

Channel title could use a horizontal shadow instead of text wrapping.

**Comment by emansom** [comment]
Much better with the menu!

Channel title could use a horizontal shadow instead of text wrapping.

![Schermafdruk van 2022-10-12 14-00-53](https://user-images.githubusercontent.com/981494/195337335-efa7f1cd-fbc5-468b-99bb-9829302e30ac.png)
