### ISSUE TITLE
Significant Audio Desync on Chromium and Webkit-based Browsers

### ISSUE THREAD

**Issue by kuoushi** [Chocobozzz/PeerTube#6438]
### Describe the current behavior

When playing a video in Chrome, Opera, Edge, or Safari (and presumably all other Chromium/Webkit browsers), videos on [my instance](https://videos.kuoushi.com) have a 2-3 second audio delay making it not in sync with the video being played. I haven't seen this on other instances, but watching a video from my instance while on another instance still seems to have this same issue.
Firefox appears to be less affected by this issue.

### Steps to reproduce

1. Go to any video hosted on [videos.kuoushi.com](https://videos.kuoushi.com/w/ibwPY42ANmFo44XDfhCNwZ) with a Chromium browser
2. Observe that audio is not synchronized with video (~00:00:12 in the above linked video, menu cursor bloop happens well after the cursor is moved)

### Describe the expected behavior

The audio plays at the correct offset without any desync from the video.

### Additional information

* PeerTube instance:
  * URL: https://videos.kuoushi.com
  * Version: 6.1.0
  * NodeJS version: Docker
  * Ffmpeg version: Docker

* Browser name, version and platforms on which you could reproduce the bug: Edge, Chrome (Desktop+Mobile), Opera (Desktop+Mobile), Safari (Mobile)
* Logs didn't show anything beyond a view happened
* No special transcode settings or plugins were used when uploading these videos to the instance

**Comment by gergob** [comment]
@kuoushi could you just download the mp4 file and try out a local player ? This might be an issue of the player as well.

**Comment by kuoushi** [comment]
@gergob Thanks for the quick reply?

I just downloaded the video and tried running it in VLC, MPC-BE, and even Windows Media Player, same issue there! Audio desync appears to be about the same.

**Comment by gergob** [comment]
@kuoushi thank you for confirming, it seems then something went wrong during transcoding. I assume you have access to the original (non-transcoded) video file and the sound is OK there.

**Comment by Chocobozzz** [comment]
Can you provide the input file URL so I try to check what happened?

**Comment by kuoushi** [comment]
@Chocobozzz 
Let me know if this link works for you:

[Original file for the example video of the issue](https://kuoushi.com/wp-content/uploads/1718/07/2023-09-30-False-Skies-01-u.mp4)

**Comment by Chocobozzz** [comment]
Remote runners are enabled on your instance? If yes what is the ffmpeg version of your remote runner + the remote runner version?

**Comment by kuoushi** [comment]
I only just today enabled remote runners because I thought the resolution of this might require re-transcoding all of my videos. All of my videos (aside from the recent two I uploaded as a test) were transcoded with ffmpeg version that came with the PeerTube docker instance.

That being said, my remote runner uses this version of ffmpeg: ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers

**Comment by Chocobozzz** [comment]
Can you tell me if you Audio Desync happens with this truncated file? https://asso.framasoft.org/drop/r/1VSEnUyPyb#qRnpQeFeb/CnNm3FqmnhVsxtMNujIoEMAM0WwEDNeS0=

**Comment by kuoushi** [comment]
Just uploaded that directly to my Peertube and the audio desync is still there when uploaded and transcode by my PeerTube instance.

https://videos.kuoushi.com/w/pYHANQKyNGZHXm88qke4Gi

**Comment by Chocobozzz** [comment]
Than you very much I was able to reproduce and fixed the bug in https://github.com/Chocobozzz/PeerTube/commit/0adbc73eb9fe2017d5fd6b0200053871d72f3b14

**Comment by kuoushi** [comment]
Thank you for fixing the issue!

Am I right to assume that I will need to re-transcode my videos when that fix goes live? Not a problem, just want to know so I can get ready to do that.

**Comment by Chocobozzz** [comment]
> Am I right to assume that I will need to re-transcode my videos when that fix goes live? Not a problem, just want to know so I can get ready to do that.

Yes I think retranscoding should fix the issue!

**Comment by kuoushi** [comment]
@Chocobozzz I believe the above issue has regressed.

Somewhere in version [6.3.x](https://github.com/Chocobozzz/PeerTube/releases/tag/v6.3.3) has started to have the same issue as the above (and currently also has the same issue in 7.0.0). It currently only occurs with the highest resolutions, but the audio desync issue doesn't happen on 240p resolutions. You can turn toggle the desync issue and makes it a bit more easily to see.

Sample (https://videos.kuoushi.com/w/kPHngdNtApoq85o9heWp8M?start=9m58s)
720p: Desync in Audio (Wrong)
240p: No Desync (Good)

Unlike the last issue, the downloaded versions of the file don't have the given above.

Same issue should happen in 6.3.x and 7.0.0 files like in the above issue in others on my instance from recently.

Should I create a new issue for this?

**Comment by Chocobozzz** [comment]
I could not reproduce, but I tried to fix the issue in https://github.com/Chocobozzz/PeerTube/commit/8a1d90dc700cdd48a1e596d6ed13f9808b8a9860

Can you try the patch? (you can update your JS server file directly)

**Comment by kuoushi** [comment]
I tried your patch above but the issue still continues after a re-transcode. I'll see what else I can figure out out to help it easier to reproduce.

**Comment by Chocobozzz** [comment]
What is your ffmpeg version?

**Comment by kuoushi** [comment]
My instance is run through Docker, so the latest version there. I'll try to get that for you.

**Comment by Chocobozzz** [comment]
Thanks, so you can try to set up a remote runner to use latest ffmpeg version: https://docs.joinpeertube.org/admin/remote-runners

**Comment by kuoushi** [comment]
I don't have a remote runner currently so I can't currently try that just yet.

I have been trying to find where this issue is happening, and have exported a small bit of video that I can get it a bit easier to check.

Source Video: https://kuoushi.com/wp-content/uploads/2025/01/2024-12-04-Twilight-Town-01-1034-1061.mp4
Transcoded in my Video: https://videos.kuoushi.com/w/uGBJipGvZuSfpxuWeM2P3n

In my instance:
1) Download the video
2) Upload/Transcode the video in PeerTube
3) Wait for all transcodes/etc running
4) Open the video in PeerTube in Firefox, no much desync issue (720p + 240p resolutions)
5) Open the video in PeerTube in Chrome/etc., desync found in Firefox at 720p, no desync at 240p
6) Download the transcoded version from PeerTube, no much desync founded (720p + 240p both fine)

Hope this is something that is reproduced for you.

The only thing I can kind of see different is that in Chrome/etc., there is a small bit of video lag when changing between resolutions. Firefox changes the resolution without issuess, though.
