### ISSUE TITLE
Cannot import/upload videos from Firefox based browsers or edit them in any browser.

### ISSUE THREAD

**Issue by RiQuY** [Chocobozzz/PeerTube#6913]
### Describe the current behavior

When I try to upload a video or importing from a URL while using a Firefox based browser like Firefox or Librewolf, after clicking on "Upload video" the connection timeouts after 15~ seconds leaving a message in the browser console and in the logs. This error also happens when tried to edit the video information of an already imported video.

I tried uploading from Chrome and Brave and there the import works fine, editing don't work in any browser. I also tried removing the nginx/caddy optimizations from my webserver having the same result.

I'm using the docker deployment of Peertube 7.0.1 without plugins and the livestreams disabled, the instance is public to see (no registration allowed), you can see it in this URL. https://video.riquy.dev/

### Steps to reproduce

1. Log in to your account from a Firefox based browser.
2. Click on upload video.
3. Upload a file or an URL (for example: https://www.twitch.tv/ricardo_stryki/video/2396762617) and wait for it to fail to connect (look at JS console)
NOTE: This also happens when tried to edit the video information of an video awaiting transcoding, the editing doesn't work in any browser.

### Describe the expected behavior

The expect behaviour is being able to upload/import videos from Firefox based browsers.

### Additional information

* PeerTube instance:
  * URL: https://video.riquy.dev/
  * Version: v7.0.1 (Docker deployment with production-bookworm tag)
  * NodeJS version: v18.20.7
  * Ffmpeg version: 5.1.6-0+deb12u1

* Browser name, version and platforms on which you could reproduce the bug: LibreWolf 135.0.1-1 or Firefox 135.0
* Link to browser console log if relevant:
Error when uploading a video from Firefox based browsers.
The related POST request to "/api/v1/videos/import" appears empty.
```
Error: Could not establish connection. Receiving end does not exist. 2 [trigger-autofill-script-injection.js:5:20](moz-extension://224d1b30-8d4a-43cf-a8d0-6ecd173c9ca7/content/trigger-autofill-script-injection.js)

/******/ (function() { // webpackBootstrap
(function () {
    // FIXME: Verify that this floating promise is intentional. If it is, add an explanatory comment and ensure there is proper error handling.
    // eslint-disable-next-line @typescript-eslint/no-floating-promises
    chrome.runtime.sendMessage({ command: "triggerAutofillScriptInjection" });
})();

/******/ })()
;
```
Error log when editing a video information from any browser:
```
https://video.riquy.dev/api/v1/videos/512/source Request Method: GET Status Code: 404 Not Found
{
    "type": "about:blank",
    "title": "Not Found",
    "detail": "Video source not found",
    "status": 404,
    "docs": "https://docs.joinpeertube.org/api-rest-reference.html#operation/getVideoSource"
}

PUT https://video.riquy.dev/api/v1/videos/512 408 (Request Timeout)
No {
  error: null
  headers: t {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
  message: "Http failure response for https://video.riquy.dev/api/v1/videos/512: 408 OK"
  name: "HttpErrorResponse"
  ok: false
  status: 408
  statusText: "OK"
  url: "https://video.riquy.dev/api/v1/videos/512"
}

Backend returned code 408, errorMessage is: Error de servidor desconocido 
{
  type: undefined
  url: "https://video.riquy.dev/api/v1/videos/512"
}
```
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`):
This is the relevant error logs I found in peertube.log
```
{"tags":["client"],"username":"riquy","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0","meta":"{\"url\":\"https://video.riquy.dev/api/v1/videos/imports/\"}","url":"https://video.riquy.dev/videos/upload#import-url","level":"error","message":"Client log: Backend returned code 0, errorMessage is: Error de servidor desconocido","label":"video.riquy.dev:443","timestamp":"2025-03-06T06:07:24.997Z"}
{"tags":["http"],"level":"info","message":"83.54.0.0 - - [06/Mar/2025:06:07:24 +0000] \"POST /api/v1/server/logs/client HTTP/1.1\" 204 - \"https://video.riquy.dev/videos/upload\" \"Firefox\"","label":"video.riquy.dev:443","timestamp":"2025-03-06T06:07:24.998Z"}
{"tags":["client"],"username":"riquy","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0","url":"https://video.riquy.dev/videos/upload#import-url","level":"error","message":"Client log: Error: Error de servidor desconocido","label":"video.riquy.dev:443","timestamp":"2025-03-06T06:07:25.002Z"}
```

The instance is behind a Caddy reverse proxy to have SSL and a domain so the webserver in the docker file is not needed.
docker-compose.yml
```
services:
  peertube:
    image: chocobozzz/peertube:production-bookworm
    container_name: peertube
    group_add:
      # HW Acceleration - getent group render | cut -d: -f3
      - "106"
    devices:  
      - /dev/dri/renderD128:/dev/dri/renderD128
    env_file:
      - peertube.env

    ports:
     - "9000:9000" # Uncomment if you use another webserver/proxy or test PeerTube in local, otherwise not suitable for production
    volumes:
      - ./data:/data
      - ./config:/config
    depends_on:
      - postgres
      - redis
      - postfix
    restart: "always"

  postgres:
    image: postgres:13-alpine
    container_name: peertube-postgres
    env_file:
      - peertube.env
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: "always"

  redis:
    image: redis:6-alpine
    container_name: peertube-redis
    volumes:
      - ./redis:/data
    restart: "always"

  postfix:
    image: mwader/postfix-relay
    container_name: peertube-postfix
    env_file:
      - peertube.env
    volumes:
      - ./opendkim/keys:/etc/opendkim/keys
    restart: "always"

```

With secrets redacted.
.env
```
# Database / Postgres service configuration
POSTGRES_USER=admin
POSTGRES_PASSWORD=_______REDACTED______
# Postgres database name "peertube"
POSTGRES_DB=peertube
# Database username and password used by PeerTube must match Postgres', so they are copied:
PEERTUBE_DB_USERNAME=$POSTGRES_USER
PEERTUBE_DB_PASSWORD=$POSTGRES_PASSWORD
PEERTUBE_DB_SSL=false
# Default to Postgres service name "postgres" in docker-compose.yml
PEERTUBE_DB_HOSTNAME=postgres

# PeerTube server configuration
# If you test PeerTube in local: use "peertube.localhost" and add this domain to your host file resolving on 127.0.0.1
PEERTUBE_WEBSERVER_HOSTNAME=video.riquy.dev
# If you just want to test PeerTube on local or use a reverse proxy.
PEERTUBE_WEBSERVER_PORT=443
PEERTUBE_WEBSERVER_HTTPS=true
# If you need more than one IP as trust_proxy
# pass them as a comma separated array:
PEERTUBE_TRUST_PROXY=["127.0.0.1", "loopback", "172.18.0.0/16", "10.10.10.1", "192.168.1.171"]

# Generate one using `openssl rand -hex 32`
PEERTUBE_SECRET=_______REDACTED______

# E-mail configuration
# Default to Postfix service name "postfix" in docker-compose.yml
# May be the hostname of your Custom SMTP server
PEERTUBE_SMTP_HOSTNAME=postfix
PEERTUBE_SMTP_PORT=25
PEERTUBE_SMTP_FROM=noreply@riquy.dev
PEERTUBE_SMTP_TLS=false
PEERTUBE_SMTP_DISABLE_STARTTLS=false
PEERTUBE_ADMIN_EMAIL=peertube@riquy.dev

# Postfix service configuration
POSTFIX_myhostname=video.riquy.dev
# If you need to generate a list of sub/DOMAIN keys
# pass them as a whitespace separated string <DOMAIN>=<selector>
OPENDKIM_DOMAINS=video.riquy.dev=peertube
# see https://github.com/wader/postfix-relay/pull/18
OPENDKIM_RequireSafeKeys=no

PEERTUBE_OBJECT_STORAGE_UPLOAD_ACL_PUBLIC="public-read"
PEERTUBE_OBJECT_STORAGE_UPLOAD_ACL_PRIVATE="private"
```

**Comment by Chocobozzz** [comment]
Hello,

Please enable [debug logs](https://docs.joinpeertube.org/admin/logs#standard-logs), restart PeerTube, reproduce and paste the PeerTube logs so we can see if it gets stuck on a particular step. :)

**Comment by RiQuY** [comment]
> Hello,
> 
> Please enable [debug logs](https://docs.joinpeertube.org/admin/logs#standard-logs), restart PeerTube, reproduce and paste the PeerTube logs so we can see if it gets stuck on a particular step. :)

I went ahead and changed the log level to debug, then I did the following:
- Restart all the peertube containers
- Login to my user "riquy"
- Try to upload a video using this URL "https://www.twitch.tv/videos/2403000403" and wait for like 2 minutes (while being stuck on the upload screen)
- Try to edit a video, change the description, thumbnail and category, click on update and wait like 2 minutes (while being stuck on the edit screen).

These are the logs:
- https://gist.github.com/RiQuY/5bb5758f69f0511dbc427a72e6c03362

I'm sorry if the logs are too much, I don't know what info is important or not so I didn't deleted anything, but if you scroll down you can see some SQL errors, if you need the logs in a different format or with a reduced size please tell me what to do and I'll try my best to give you relevant info.

Thanks

**Comment by RiQuY** [comment]
In this comment I'll try to provide more context about my deployment hoping it shows any light on why I'm encountering this issue, if you think some information is not useful feel free to ignore it.

> I think there is a timeout between your reverse proxy and peertube 🤔

It indeed looks like a timeout error when I try to reproduce the issue because the bar that is shown by peertube at the top of the screen to indicates that's is trying to do something never fills, but I didn't changed anything in the configuration of the reverse proxy or in the docker-compose files, in this exact deployment I already uploaded 400+ videos before in the same peertube version without issue.

I don't understand why the timeout is only happening in the upload/edit step, I can interact with the instance properly, logging in, checking every menu including the admin menus and watching videos, also I checked that other people can see the videos too.

The only thing I do regularly is check if there is new images available of the containers following these steps:
- turn off the containers
- pull the images
- turn on the containers again
- delete the old images

But this is also strange because even if the Peertube version is the same, the production-bookworm image shows that it's updated every day https://hub.docker.com/r/chocobozzz/peertube/tags 
Maybe doing this update process I damaged the postgres image in some way? I also regularly update the system it's deployed on, to get kernel or docker updates (it's based on debian bookwork).

Reverse proxy
--
I also tried to simplify the reverse proxy settings removing the suggested NGINX optimizations (I use Caddy) but I get the same result, as you said, a timeout when uploading or editing videos.

This are the different reverse proxy configurations that I tried:
- No optimizations: https://gist.github.com/RiQuY/c5f6d3c517bc94a457e46988dfccbd2d
- Some optimizations: https://gist.github.com/RiQuY/a4e5a81c36f1808d5d339d6cf33660ce

I'm aware that you don't offer support for optimizations in Caddy, only NGNIX, I'm only showing what I tried to provide more context and I'm fine using the no optimization variant but I'm getting the same error.

SSL
--
I checked if there is some problem with the HTTPS cert but it's managed by Caddy and it's working properly in my other subdomains like https://live.riquy.dev so I don't think where the problem is.

Ports/Firewall
--
I checked if there is any collision in the exposed ports of the docker containers I have deployed in the same machine, and I couldn't find none.

![Image](https://github.com/user-attachments/assets/16b7c171-b6e9-4ad6-ab8a-0f8fb94f7f11)

Also, these are the firewall rules I have configured in the VPS that's it's used a reverse proxy. (51821 is the Wireguard port)

![Image](https://github.com/user-attachments/assets/fe247578-a9e2-41c9-b391-d1a67874053a)

I host every service on a dedicated machine on my home, the only configuration in the VPS is the Caddy reverse proxy, the wireguard point-to-point tunnel and nothing else.

**Comment by RiQuY** [comment]
UPDATE: I updated my instance to PeerTube 7.1 following the docs https://docs.joinpeertube.org/install/docker#upgrade and the issue is still happening.
If you need more info/logs please tell and I will try my best to provide them to help with the resolution of this issue, I literally cannot upload content to my instance because of this.

**Comment by RiQuY** [comment]
@Chocobozzz 
I tried more things, I enabled the docker webserver and certbot containers (and generated the SSL cert) https://docs.joinpeertube.org/install/docker#webserver , now the instance has the recommended NGNIX configuration and Caddy is used exclusively as a reverse proxy:
- Browser - video.riquy.dev -> Caddy proxies to the IP:Port of the nginx ->  nginx-webserver handles the request

Updated configuration, Caddy, Docker-compose and .env (secrets redacted):
- https://gist.github.com/RiQuY/1d6f33b3fd73de6b6f33c327907a0274
- NGINX config used (unmodified): https://github.com/Chocobozzz/PeerTube/blob/master/support/nginx/peertube

Sadly this doesn't solve the issue yet, the only change is that the timeout expires faster (in 15 seconds and I got the error faster), these are the tests I made:
- Error while trying to import a video URL using Firefox based browsers.
- Error while trying to edit a video information using Firefox based browsers.
- Import works successfully when importing a video URL using Chromium based browsers (but can't change info).
- Error while trying to edit a video information using Chromium based browsers.

I want to point out that the instance worked fine in the past without any configuration change or version update, I uploaded 400+ videos without errors, one day it started having those problems. Looking at the logs and the weird behavior makes me believe there is something wrong with the code that handles API requests maybe it starts failing at X number of uploaded videos or fails because of the User Agent (weird).

Logs with debug on:
- https://gist.github.com/RiQuY/37d0fdaf6176c79e3b6df1f1110e13c9
(if you see an error of an incorrect URL in the import ignore it, I copied it wrong in one test)

At this point I'm out of ideas to try, I doubt it is a configuration issue and I don't know what more to change, I can provide you with an account in the instance with admin privileges if that helps. Also, where can I look for more help with this issue?

**Comment by Chocobozzz** [comment]
Do you have logs from nginx or caddy explaining why it throws a 502 error that I see in the logs?

**Comment by RiQuY** [comment]
Sorry about the late response, I didn't see the GitHub notification.

These are the logs, from Caddy (the reverse-proxy) and the NGINX inside Docker.
- https://gist.github.com/RiQuY/1d787742c5ae853b78f2b2aecba90020

While using the nginx container there are no error logs for Caddy, only access logs. In the ngnix logs the relevant line I could find is this one.
```
2025/04/02 04:46:30 [error] 11#11: *74 connect() failed (111: Connection refused) while connecting to upstream, client: 10.10.10.1, server: video.riquy.dev, request: "GET /api/v1/videos/95c6b3e0-9d59-4bb8-8e28-744bc2dfce1d/captions HTTP/2.0", upstream: "http://[fdab:e4b3:21a2:ef1b::42]:9000/api/v1/videos/95c6b3e0-9d59-4bb8-8e28-744bc2dfce1d/captions", host: "video.riquy.dev", referrer: "https://video.riquy.dev/my-library/videos"
```

But it makes no sense that it is failing, because all the necessary IPs are added in there
```
PEERTUBE_TRUST_PROXY=["127.0.0.1", "loopback", "172.18.0.0/16", "10.10.10.1", "10.10.10.10", "192.168.1.171", "198.251.84.139"]
```

Also if it was a communication error with the IP 10.10.10.1 shouldn't be able to access the website at all or watch videos. And the error only happens when uploading videos from firefox or when editing the video information on any browser, so specific API request. Also you can check the log file ngnix-peertube.access.log (in the Gist URL) where it shows it is doing many succesfull requests to 10.10.10.1

I doubt this could be useful but these are the Wireguard configurations I'm using (with sensitive info redacted):
- https://gist.github.com/RiQuY/ba9319ef51a3bab7b7bd3db9c5b0ebb1

**Comment by RiQuY** [comment]
@Chocobozzz I think there is something wrong with some file in the peertube config that is causing all of this (I don't know which file).
I suspect this because I cannot load the "Basic" tab on Settings - Configuration - Basic, it shows the following errors.

Is there any way to restore or regenerate that configuration?

```
ERROR DOMException: Node.insertBefore: The new child is an ancestor of the parent - chunk-SEGKBXR2.js:15:26256

Error: Could not establish connection. Receiving end does not exist. - trigger-autofill-script-injection.js:5:20
```

The connection error looks very similar to the one I have in the menus to upload/edit videos. 

![Image](https://i.imgur.com/p0iWDl9.png)

**Comment by Chocobozzz** [comment]
I think it's the same bug as https://github.com/Chocobozzz/PeerTube/issues/7007 that should be fixed in next version

**Comment by RiQuY** [comment]
> I think it's the same bug as [#7007](https://github.com/Chocobozzz/PeerTube/issues/7007) that should be fixed in next version

I don't know what was the root cause of the issue but it is fixed now, I can edit and upload videos. I'm running PeerTube 7.2.1.
Proof of a video I uploaded today: https://video.riquy.dev/w/aJonY5Z4vusjmiUJGiqSN6

Thank you for fixing the bug I hope this doesn't break again for no reason, it was a tricky issue. I'll go ahead and close the issue, if you think there is something left to do you can re-open it.

**Comment by RiQuY** [comment]
It started happening again, this makes no sense.
I queued up 10 videos for upload and when I checked 1~ hour later the whole domain was innacessible and the uploads said "File locked", 2 of the videos did manage to get uploaded but the URL doesn't load, I restarted the webserver (Caddy) and the Docker containers of PeerTube and it fixed nothing (at least the domain started working again). Back to not being able to edit video information or upload new videos.

I'm tired, I don't know what to do or what is causing this, I changed nothing on the deployment since it started working again.

**EDIT**: And it fixed itself after some hours.
Thinking about this behavior I suspect there is something wrong with the job scheduler that gets overloaded when there are many jobs active/queued and instead of making the jobs fail it leaves the job scheduler on a unresponsive state on which it cannot accept new jobs like editing/uploading videos (not even restarting the containers), and after some unknown time it decides to get working again setting all the jobs to "fail".

Knowing this, I'll just avoid to upload/transcode more than 1 video at the same time hoping that it prevents the job scheduler from hanging, that's the only "workaround" I can think of. Even when the machine I'm running is not bad, it has 20GB of RAM and a Intel Celeron N5105 just for running a PeerTube instance and a personal website.

**Comment by RiQuY** [comment]
@Chocobozzz I updated to 8.0.2 (Postgres and Redis upgrade too) and the error started happening again, although only when uploading videos.

I get the error right away with the request saying "File locked" in the Network Inspector and red bar replacing the upload progress or after ~15 minutes of an upload, having to reset the upload to get the error in ~15 minutes again. I'm not overloading the instance, this happening with a 6GB video single upload.

<img width="1730" height="180" alt="Image" src="https://github.com/user-attachments/assets/45f539a0-87fa-4880-a0c3-43f8a80531af" />

```json
{"error":{"code":"FileLocked","message":"File locked"}}
```

The website is functional when trying to watch a video but uploading is not working.

Is there other way to upload videos, like a cli? I don't mind changing my upload method if that makes it work.

<img width="2274" height="149" alt="Image" src="https://github.com/user-attachments/assets/af1d1a0e-a34c-418e-a3d6-fce92a4d538c" />

<img width="492" height="1043" alt="Image" src="https://github.com/user-attachments/assets/c1c773fd-dd16-4587-aaf4-bb245223ecd9" />

I've also tried using the PeerTube CLI but I get a socket error when I try to upload, even when the auth was succesfull.

<img width="1071" height="144" alt="Image" src="https://github.com/user-attachments/assets/ac46dde5-d3c6-4d35-8700-32dbdae3cbdf" />

**Comment by RiQuY** [comment]
**UPDATE**: I added part of the nginx config (translated to caddy) to try to solve the issue thinking it was some misconfiguration or timeout error but I still get the same behaviour. (I'm using Firefox)

Caddy config:
- https://gist.github.com/RiQuY/e7eeb6c0a53e72f94ca928f564d6650e

peertube-cli
--

Container logs

<img width="1642" height="37" alt="Image" src="https://github.com/user-attachments/assets/c118c109-a561-4e71-bad1-f4d4b15e8f22" />

cli logs

<img width="1351" height="143" alt="Image" src="https://github.com/user-attachments/assets/0637d97d-a496-4493-b59f-c0b03e3aa56b" />

Web upload.
--

Container logs

<img width="1637" height="43" alt="Image" src="https://github.com/user-attachments/assets/8672a906-5ee4-43d6-81c9-00694902d3a0" />

```
peertube  | [video.riquy.dev:443] 2026-02-12 03:52:02.654 info: 10.10.10.1 - - [12/Feb/2026:03:52:02 +0000] "PUT /api/v1/videos/upload-resumable?upload_id=af63af4c8601a015-4576a174f120a045-583269ec07e6a4e5-ef2602764c1dfac1 HTTP/1.1" 308 - "https://video.riquy.dev/videos/publish?uploading=true" "Mozilla/5.0 (X11; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0"
peertube  | [video.riquy.dev:443 uploadx] 2026-02-12 03:52:05.013 error: [error]: {
peertube  |   name: 'UploadxError',
peertube  |   stack: 'UploadxError: FileLocked\n' +
peertube  |     '    at fail (/app/node_modules/.pnpm/@uploadx+core@6.1.9/node_modules/@uploadx/core/lib/utils/errors.js:81:27)\n' +
peertube  |     '    at DiskStorage.lock (/app/node_modules/.pnpm/@uploadx+core@6.1.9/node_modules/@uploadx/core/lib/storages/storage.js:164:37)\n' +
peertube  |     '    at DiskStorage.write (/app/node_modules/.pnpm/@uploadx+core@6.1.9/node_modules/@uploadx/core/lib/storages/disk-storage.js:62:20)\n' +
peertube  |     '    at async Uploadx.put (/app/node_modules/.pnpm/@uploadx+core@6.1.9/node_modules/@uploadx/core/lib/handlers/uploadx.js:63:22)',
peertube  |   message: 'FileLocked',
peertube  |   uploadxErrorCode: 'FileLocked',
peertube  |   detail: '',
peertube  |   request: {
peertube  |     headers: {
peertube  |       host: 'video.riquy.dev',
peertube  |       'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0',
peertube  |       'content-length': '67108864',
peertube  |       accept: '*/*',
peertube  |       'accept-encoding': 'gzip, deflate, br, zstd',
peertube  |       'accept-language': 'es-ES,es;q=0.9,en-US;q=0.8,en;q=0.7',
peertube  |       authorization: 'REDACTED',
peertube  |       'content-range': 'bytes 3306160128-3373268991/7006992876',
peertube  |       'content-type': 'application/octet-stream',
peertube  |       cookie: 'clientLanguage=en',
peertube  |       origin: 'https://video.riquy.dev',
peertube  |       referer: 'https://video.riquy.dev/videos/publish?uploading=true',
peertube  |       'sec-fetch-dest': 'empty',
peertube  |       'sec-fetch-mode': 'cors',
peertube  |       'sec-fetch-site': 'same-origin',
peertube  |       'sec-gpc': '1',
peertube  |       te: 'trailers',
peertube  |       via: '2.0 Caddy',
peertube  |       'x-forwarded-for': '',
peertube  |       'x-forwarded-host': 'video.riquy.dev',
peertube  |       'x-forwarded-proto': 'https',
peertube  |       'x-real-ip': 'REDACTED_HOME_IP'
peertube  |     },
peertube  |     method: 'PUT',
peertube  |     url: '/upload-resumable?upload_id=af63af4c8601a015-4576a174f120a045-583269ec07e6a4e5-ef2602764c1dfac1'
peertube  |   }
peertube  | }
peertube  | [video.riquy.dev:443] 2026-02-12 03:52:05.015 info: 10.10.10.1 - - [12/Feb/2026:03:52:05 +0000] "PUT /api/v1/videos/upload-resumable?upload_id=af63af4c8601a015-4576a174f120a045-583269ec07e6a4e5-ef2602764c1dfac1 HTTP/1.1" 423 55 "https://video.riquy.dev/videos/publish?uploading=true" "Mozilla/5.0 (X11; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0"
```
Frontend logs

<img width="1962" height="165" alt="Image" src="https://github.com/user-attachments/assets/a01ebe16-c421-4362-b693-8d0bdb0cb7b2" />

---

<img width="493" height="995" alt="Image" src="https://github.com/user-attachments/assets/30e02555-43f0-4a6b-a6de-d8bb91e3975c" />

---

<img width="493" height="931" alt="Image" src="https://github.com/user-attachments/assets/d03ef0d5-e278-4374-be5b-35b0872d4ac9" />

```json
{"error":{"code":"FileLocked","message":"File locked"}}
```

Caddy logs
--

```
Feb 11 18:56:46 localhost caddy[2424207]: {"level":"info","ts":1770865006.0881228,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
Feb 11 18:56:46 localhost caddy[2424207]: {"level":"warn","ts":1770865006.0882611,"logger":"http","msg":"HTTP/2 skipped because it requires TLS","network":"tcp","addr":":80"}
Feb 11 18:56:46 localhost caddy[2424207]: {"level":"warn","ts":1770865006.0883338,"logger":"http","msg":"HTTP/3 skipped because it requires TLS","network":"tcp","addr":":80"}
Feb 11 18:56:46 localhost caddy[2424207]: {"level":"info","ts":1770865006.0883641,"logger":"http.log","msg":"server running","name":"remaining_auto_https_redirects","protocols":["h1","h2","h3"]}
Feb 11 18:56:46 localhost caddy[2424207]: {"level":"info","ts":1770865006.0884118,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["riquy.dev","video.riquy.dev","www.riquy.dev"]}
Feb 11 18:56:46 localhost caddy[2424207]: {"level":"info","ts":1770865006.08854,"logger":"http","msg":"servers shutting down with eternal grace period"}
Feb 11 18:56:46 localhost caddy[2424207]: {"level":"info","ts":1770865006.089657,"msg":"autosaved config (load with --resume flag)","file":"/var/lib/caddy/.config/caddy/autosave.json"}
Feb 11 18:56:46 localhost caddy[2424207]: {"level":"info","ts":1770865006.0901814,"logger":"admin.api","msg":"load complete"}
Feb 11 18:56:46 localhost systemd[1]: Reloaded caddy.service - Caddy.
Feb 11 18:56:46 localhost caddy[2424207]: {"level":"info","ts":1770865006.0968592,"logger":"admin","msg":"stopped previous server","address":"localhost:2019"}
```

UPDATE
--
 I adapted the nginx config to caddy (except the static parts because it's a reverse proxy) and add global timeouts of 45m in top of the config file, I also had to add `PUT` in the `@bad not method POST PUT HEAD` lines. I uploaded 3 videos correctly today but at the next day, the error keep happening again, I'm so tired tbh, why this keeps happening on Firefox/Brave. Sometimes this is solved restarting the container but it is not a consistent workaround.

I also find important to mention that the video upload speed always has been extremely slow even when I have 1Gbps connection, could this be related somehow? I made bandwidth speed tests on all the machines and the lowest result I've got is 800Mbps but a single 5GB video upload to Peertube could take up to an hour.

I haven't tested the peertube-cli with this new config yet, only the web upload.

Caddy config:
- https://gist.github.com/RiQuY/e7eeb6c0a53e72f94ca928f564d6650e

**Comment by Chocobozzz** [comment]
> I also find important to mention that the video upload speed always has been extremely slow even when I have 1Gbps connection, could this be related somehow? 

It's slow only on firefox? Or on all web browsers?

**Comment by RiQuY** [comment]
> > I also find important to mention that the video upload speed always has been extremely slow even when I have 1Gbps connection, could this be related somehow?
> 
> It's slow only on firefox? Or on all web browsers?

All web browsers that I've tried, Firefox, LibreWolf and Brave. For example for uploading a video of 6GB it uploads around 0.05%/0.03% per second. (I have 1Gbps up/down speed)

One time I tried copying the localStorage variables of my logged in account (from video.riquy.dev to 192.168.1.171:9000) to avoid the limitation of not being able to log in without passing through the domain URL to check if this was problem with the domain or the internet but even uploading a video through the local network has the same speed (slow).

I ran speed tests on every machine I could and I always get 900Mbps up/down (my home network speed) or 4500Mbps up/down (my VPS speed). So I have no idea why the uploads are so slow.

This is unrelated to the main issue but a feature like "Import from folder in the server" will avoid this issue completely, the upload will be still broken for me, but I guess with that feature the videos will load into peertube with no issue, because that will skip the "move the files from other machine through the internet" part.

**Comment by RiQuY** [comment]
I started to ignore the "upload from file" option and now I'm importing videos from YouTube, that option at least works consistently.

This is very sad because it defeats the whole purpose of having PeerTube in the first place (stop using YouTube), but it is what it is.

So now I'm using PeerTube as a backup for my videos rather than my main platform.

**Comment by Chocobozzz** [comment]
Do you have a reverse proxy in front of Caddy?

**Comment by RiQuY** [comment]
> Do you have a reverse proxy in front of Caddy?

Caddy is my reverse proxy.

I have this deployment:
- VPS: Caddy with auto TLS routing video.riquy.dev:443 to 10.10.10.10:9000.
- Home network: PeerTube deployed in a docker container listening on port 9000, the deployment is on a NAS with Debian 12.

The connection between the VPS and my home network is made through a Wireguard tunnel.

**Comment by Chocobozzz** [comment]
I'm sorry but I can't help here. There are many components in front of your PeerTube instance, that are not related to PeerTube. I suggest trying to move PeerTube on a VPS with the same reverse proxy first, to ensure it's not related to Caddy. Then, disable Wireguard, etc. It could be for example a MTU issues.

**Comment by RiQuY** [comment]
> I'm sorry but I can't help here. There are many components in front of your PeerTube instance, that are not related to PeerTube. I suggest trying to move PeerTube on a VPS with the same reverse proxy first, to ensure it's not related to Caddy. Then, disable Wireguard, etc. It could be for example a MTU issues.

Is not Wireguard nor Caddy, (like I mentioned 2 messages above https://github.com/Chocobozzz/PeerTube/issues/6913#issuecomment-3935816416) I tested uploading videos from the local network directly (moving the LocalStorage variables in the browser from video.riquy.dev to 192.168.1.171:9000) and it's the same slow speed or upload failures.

Also I don't think I have many components in my deployment, Caddy in a VPS connects with the PeerTube docker deployment through a Wireguard tunnel in my home network, the only "extra thing" there is Wireguard but every other component is required to make PeerTube work like the docs mention.

But I get it, this a 1 year old issue and the only thing breaking is that most of the time the "Upload video from file" fails or it has extremely low upload speed, so it may seem not important overall if it's hard to reproduce.
