### ISSUE TITLE
The `util.isArray` API is deprecated

### ISSUE THREAD

**Issue by spirillen** [Chocobozzz/PeerTube#7047]
### Steps to reproduce

(using peetube-cli)

```bash
$  upload_peertube_videos.sh --tags "U2, Ireland, IrishHistory, BloodySunday, SundayBloodySunday"
Please select a channel name from the following options:
1. audiovideos
2. lyricvideos
3. musicvideos
4. spirillen_musi
5. videos
Enter the number corresponding to your choice: 3
Uploading Sunday Bloody Sunday (Live From Red Rocks Amphitheatre, Colorado, USA ⧸ 1983 ⧸ Remastered 2021) - 2009-12-14 00:01 video...
(node:3980235) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Video Sunday Bloody Sunday (Live From Red Rocks Amphitheatre, Colorado, USA ⧸ 1983 ⧸ Remastered 2021) - 2009-12-14 00:01 uploaded.
```

### Additional information

* PeerTube instance: 
  * URL: https://tube.matrix.rocks
  * Version: **7.2.0-rc.1**
  * NodeJS version: **v22.16.0**
  * Ffmpeg version: **N-71064-gd5e603ddc0-static**

* Browser name, version and platforms on which you could reproduce the bug: N/A
* Link to browser console log if relevant: N/A
* Link to server log if relevant (`journalctl` or `/var/www/peertube/storage/logs/`): N/A

**Comment by spirillen** [comment]
@Chocobozzz https://github.com/if-you-want-peace-prepare-for-war/Peertube-tool

**Comment by Chocobozzz** [comment]
Can you paste the output of `peertube-cli --version`? If it's 1.0.2, can you use `node --trace-deprecation $(which peertube-cli)` in your script?

**Comment by spirillen** [comment]
Sure, report back after next use of the script

``
peertube-cli --version
1.0.2
```

**Comment by Chocobozzz** [comment]
Please use `node --trace-deprecation /usr/.../peertube-cli` inside your script, instead of `peertube-cli` directly, on these lines: https://github.com/if-you-want-peace-prepare-for-war/Peertube-tool/blob/master/upload_peertube.sh#L154

**Comment by spirillen** [comment]
> Please use `node --trace-deprecation /usr/.../peertube-cli` inside your script, instead of `peertube-cli` directly, on these lines: https://github.com/if-you-want-peace-prepare-for-war/Peertube-tool/blob/master/upload_peertube.sh#L154

Updated in https://github.com/if-you-want-peace-prepare-for-war/Peertube-tool/blob/4c0b7658ae0e82cc06fe1966638c59f50475dad8/upload_peertube.sh#L46

will test when I've rested.

**Comment by spirillen** [comment]
made the changes, and haven't been able to reproduce this time, will try again.

New full logs: https://framagit.org/spirillen/peertube-debug/-/tree/master/logs-2025-06-14?ref_type=heads

**Comment by spirillen** [comment]
Hi everyone,

I have not been able to reproduce any of these issues in version 7.0.2. Therefore, I am assuming that they are solely related to version 7.0.2-rc1

**Comment by spirillen** [comment]
Start getting this error on bigger files, even there are no file size limit (upload), and uploading with admin account


```bash
upload_peertube_videos.sh --skip-description-check --skip-image-check 
Please select a channel name from the following options:
1. audiovideos
2. lyricvideos
3. musicvideos
4. spirillen_musi
5. videos
Enter the number corresponding to your choice: 3
Upload failed for Lady Gaga - Live at Coachella Festival 2025 [2160p]. Output:
Uploading Lady Gaga - Live at Coachella Festival 2025 [2160p] video...
(node:748820) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
    at FormData.append (file:///usr/lib/node_modules/@peertube/peertube-cli/dist/peertube.js:38056:16)
    at RequestBase.field (file:///usr/lib/node_modules/@peertube/peertube-cli/dist/peertube.js:43833:29)
    at buildFields (file:///usr/lib/node_modules/@peertube/peertube-cli/dist/peertube.js:67625:11)
    at makeUploadRequest (file:///usr/lib/node_modules/@peertube/peertube-cli/dist/peertube.js:67522:3)
    at VideosCommand.postUploadRequest (file:///usr/lib/node_modules/@peertube/peertube-cli/dist/peertube.js:76513:12)
    at VideosCommand.buildLegacyUpload (file:///usr/lib/node_modules/@peertube/peertube-cli/dist/peertube.js:84585:28)
    at VideosCommand.upload (file:///usr/lib/node_modules/@peertube/peertube-cli/dist/peertube.js:84572:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async run (file:///usr/lib/node_modules/@peertube/peertube-cli/dist/peertube.js:85527:5)
    at async _Command.<anonymous> (file:///usr/lib/node_modules/@peertube/peertube-cli/dist/peertube.js:85505:7)
Aborted: user quota is exceeded or video file is too big for this PeerTube instance.
```

<img width="765" height="593" alt="Image" src="https://github.com/user-attachments/assets/4f4a48dd-4a1a-4741-86f3-aa46ebb472d9" />

**Comment by Chocobozzz** [comment]
Thank you! Please try 1.0.3 that should fix the deprecation warning

**Comment by spirillen** [comment]
Hey @Chocobozzz 

Its me laying on my knee's thanking you for your awesome work and efforts to make the programs working; would which I good contribute with more than idea and error reporting.

this said. it's still not all there...

```
'Miss Saigon: 25th Anniversary Performance (2016).desciption'  'P!NK - The Truth About Love Tour (2013).mkv'*
'Miss Saigon: 25th Anniversary Performance (2016).jpg'         'ZZ Top - Live at Montreux 2013.description'
'Miss Saigon: 25th Anniversary Performance (2016).mkv'*        'ZZ Top - Live at Montreux 2013.jpg'
'P!NK - The Truth About Love Tour (2013).description'          'ZZ Top - Live at Montreux 2013.mkv'*
'P!NK - The Truth About Love Tour (2013).jpg'
```

<img width="638" height="261" alt="Image" src="https://github.com/user-attachments/assets/156f9201-4a85-449f-8b06-f20d6b080930" />

```
upload_peertube_videos.sh -t "concert,live,pop,rock"
Please select a channel name from the following options:
1. audiovideos
2. lyricvideos
3. musicvideos
4. spirillen_musi
5. videos
6. nsfw
Enter the number corresponding to your choice: 3
Description file Miss Saigon: 25th Anniversary Performance (2016).description does not exist.
Upload failed for P!NK - The Truth About Love Tour (2013). Output:
Uploading P!NK - The Truth About Love Tour (2013) video...
Aborted: user quota is exceeded or video file is too big for this PeerTube instance.
```
