### ISSUE TITLE
Translate page titles too

### ISSUE THREAD

**Issue by bristow** [Chocobozzz/PeerTube#793]
* **PeerTube version or URL:** https://peertube2.cpy.re/
* **Browser name/version:** Firefox
* **NodeJS version:** ?

* **What is the expected behaviour?** Titles of HTML pages should be in french
* **What do you see instead?** They stayed in English

In the menu, 'More' is also not translated.

Thanks :)

**Comment by Chocobozzz** [comment]
Thanks, for the more it should be fixed: https://github.com/Chocobozzz/PeerTube/commit/b63e428e8bf1ed1457ab1888350809bd78ce4d2f

**Comment by KRtekTM** [comment]
I translated the PeerTube to the Czech language which is now visible on the instance mentioned above.
Now I see few issues:

https://peertube2.cpy.re/about/peertube
Everything is translated except of string "How does PeerTube compare with YouTube?"
In the Zanata, the source string was "How does PeerTube compares to YouTube?" which was translated to CZ.

On the same page, the string "About PeerTube" is correctly translated but the page title (in <title> html tag) is still in english.


On the page with video player, there is notification bar with untranslated string "The sharing system used by this video implies that some technical information about your system (such as a public IP address) can be sent to other peers." which source is Zanata was "The sharing system used by this video implies that some technical information about your system (such as a public IP address) can be accessed publicly."

**Comment by KRtekTM** [comment]
+ I fixed two strings in Czech language, please can you again merge it to github so I can acquire the latest version? (I know it's out of scope of this task but I don't want to create new ticket on it). BIG THANKS

**Comment by SerCom-KC** [comment]
More untranslatable strings: 
https://github.com/Chocobozzz/PeerTube/blob/1cfa8d6809d941c703e12ef30a5161d1901b1874/client/src/app/videos/%2Bvideo-edit/shared/video-edit.component.html#L158
https://github.com/Chocobozzz/PeerTube/blob/1cfa8d6809d941c703e12ef30a5161d1901b1874/client/src/app/videos/%2Bvideo-edit/shared/video-edit.component.html#L166
https://github.com/Chocobozzz/PeerTube/blob/1cfa8d6809d941c703e12ef30a5161d1901b1874/client/src/app/videos/%2Bvideo-edit/shared/video-edit.component.html#L174
https://github.com/Chocobozzz/PeerTube/blob/1cfa8d6809d941c703e12ef30a5161d1901b1874/client/src/app/videos/%2Bvideo-edit/shared/video-edit.component.html#L182

**Comment by SerCom-KC** [comment]
Also, regarding of date formatting, can we specify the actual format for each language instead of forcing everyone to use, say, `MM YYYY` (which I believe is the current behavior in the date selector)?
e.g. In Chinese we prefer `YYYY年MM月`。

**Comment by rigelk** [comment]
@SerCom-KC I added the string to translate in cc3d1dce. Thanks for spotting them!

**Comment by SerCom-KC** [comment]
Even more untranslatable strings (sorry but if you prefer a new issue for this let me know):
https://github.com/Chocobozzz/PeerTube/blob/923406990334d133a49a283629322d1bbb521ecc/client/src/app/%2Badmin/config/edit-custom-config/edit-custom-config.component.ts#L19
https://github.com/Chocobozzz/PeerTube/blob/923406990334d133a49a283629322d1bbb521ecc/client/src/app/%2Badmin/config/edit-custom-config/edit-custom-config.component.ts#L29

Also @rigelk Zanata doesn't seem to be updated?

**Comment by rigelk** [comment]
@SerCom-KC it's fine ; Zanata is updated manually by @Chocobozzz so it might take some days before we do the operation.

Btw @Chocobozzz I don't see an elegant way of translating these string, since they are in static attributes.

**Comment by Chocobozzz** [comment]
@SerCom-KC Thanks, I fixed it in https://github.com/Chocobozzz/PeerTube/commit/3827c3b3488845f4235714e92eea439423df2909

**Comment by SerCom-KC** [comment]
@Chocobozzz Thank you!
Here's another bunch: every `.send` occurrence in https://github.com/Chocobozzz/PeerTube/blob/ad76628b17ff8f25d3402d6d669b274116bbf76c/server/middlewares/validators/users.ts

**Comment by Chocobozzz** [comment]
@SerCom-KC I created a separate issue: https://github.com/Chocobozzz/PeerTube/issues/1122

**Comment by Folatt** [comment]
Can "Jobs" in the admin menu be changed into something more French?

**Comment by AlphaShadows77** [comment]
Some titles are still missing in Zanata (With example from [iriseden](https://peertube.iriseden.eu))
- Discover videos => https://peertube.iriseden.eu/videos/overview
- Trending videos => https://peertube.iriseden.eu/videos/trending
- Recently added videos => https://peertube.iriseden.eu/videos/recently-added

**Comment by Chocobozzz** [comment]
Implemented in https://github.com/Chocobozzz/PeerTube/commit/f29f487ef8892453a481628a6a3cff802dc89213 :tada:

**Comment by bristow** [comment]
We need to translate now, it's done in french : https://weblate.framasoft.org/projects/peertube/
