### ISSUE TITLE
Login not working on development Instance

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#930]
* **PeerTube version or URL:** v1.0.0-beta.10
* **Browser name/version:** Firefox 61, Chromium 68 on latest Manjaro
* **NodeJS version:** v10.9.0

I set up a local development instance according to the [contribututing instructions](https://github.com/Chocobozzz/PeerTube/blob/develop/.github/CONTRIBUTING.md#develop). Btw it seems they are missing instructions to enable the required SQL extensions (I did that too). Compilation seems fine, the only errors I can see in the terminal are these, but they don't seem to break anything:
```
[localhost:9000] 2018-08-18 18:57:29.958 error: Error in Redis client.
[1] [0] [nodemon] app crashed - waiting for file changes before starting...
```

* **What is the expected behaviour?**
I can load Peertube normally in my browser and login as admin.

* **What do you see instead?**
When I open the page, it shows a red box with "Error: Unknown error" in the bottom right. Additionally, trying to login with root/test results in an error "Unknown error".

* **Browser console log if useful (Gist/Pastebin...):**
After loading the page, I get multiple of these warnings and errors in the browser console:
https://gist.github.com/Nutomic/bb6993bb7a0b8ed3911ababeebbefced

Submitting any username/password results in the following messages:
https://gist.github.com/Nutomic/2660b1fec86c66f29e230236c153f709

* **Server log if useful (Gist/Pastebin...):**
nothing I could find here

**Comment by Jorropo** [comment]
Have you installed an redis server and setup login and password for redis ?
If yes : is your dB id unique ?

**Comment by Chocobozzz** [comment]
> Btw it seems they are missing instructions to enable the required SQL extensions (I did that too)

Could you make a PR? :)

There is an error in you redis configuration I think. Are you up to date with the `develop` branch? We fixed an issue with the logging system, but it seems there is still the bug on your version because we don't see what is the "Redis client error".

**Comment by Nutomic** [comment]
I installed redis, but I hadn't created a [Peertube system user](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/production.md#peertube-user), which I assume you are referring to. However, that didn't fix the problem for me. Which database ID do you mean, and how can I check it?

With the develop branch (or latest master), the build fails completely with a lot of errors:

https://gist.github.com/Nutomic/9625e5c5396213a7c7730f0f49b4bcde

I created a PR at #940 with everything that I've done so far (other than the instructions in the existing contributing.md and dependencies.md documents).

**Comment by Chocobozzz** [comment]
@Nutomic When you pull or change the branch, do not forget to reinstall node modules too with `yarn install --pure-lockfile`. It's the reason why your build fails.

> Edit: Regarding redis, I installed it along with the other dependencies via pacman, but I didn't do anything else with it (as there is no mention in the instructions).

Did you `systemctl start redis`?

**Comment by Nutomic** [comment]
Thanks, it's working now! Not sure what the original problem was, but apparently it was some problem with the master branch. And then I didn't know that I would have to reinstall the modules after switching the branch.

So all I needed to fix my problem was:
```
git checkout develop
yarn install --pure-lockfile
```
