### ISSUE TITLE
4K video fails to play in many browsers, choppy in others

### ISSUE THREAD

**Issue by scanlime** [Chocobozzz/PeerTube#995]
I know this is a very broad bug that should probably be split per-platform once we have more data, but I didn't see anything yet for tracking 4K playback issues.

I tried uploading a 4K test video:
https://diode.zone/videos/watch/6f111ebd-d595-4b01-97b1-903d9a694665

Then I asked some folks on Twitter to test it:
https://twitter.com/scanlime/status/1035556043873349632

People with fast computers and network could watch it smoothly only after the file finished downloading. Some phones that support 4K YouTube seem not to support 4K here.

Obviously needs more investigation, but I thought it would be useful to collect data here and triage the issues into bite-sized bugs to work on.

**Comment by BehemothDev** [comment]
I have fast computers and network.
The video work with Firefox or Chrome / windows and mobile phone Android / Qwant.
But sometime the video stop and loader continually load at the end (don't propose replay) or in the middle.
"People with fast computers and network could watch it smoothly only after the file finished downloading." => I don't repruce probleme with Firefox/Windows. I can't test with mobile phone, the video load less than 1s ...

LOGS : 
1/
DOMException: The play() request was interrupted by a new load request. https://goo.gl/LdLk22

2/
Error: macroTask 'requestAnimationFrame': can not transition to 'running', expecting state 'scheduled', was 'notScheduled'.

**Comment by Chocobozzz** [comment]
> But sometime the video stop and loader continually load at the end (don't propose replay) or in the middle.

I think this bug should be fixed on develop branch. You can try to reproduce on https://peertube2.cpy.re/

**Comment by BehemothDev** [comment]
> But sometime the video stop and loader continually load at the end (don't propose replay) or in the middle. I think this bug should be fixed on develop branch. You can try to reproduce on https://peertube2.cpy.re/
It's work fine in develop branch.
> People with fast computers and network could watch it smoothly only after the file finished downloading. 
I Reproduce this in production but not in develop branch. I think it was impact with first point.

The last point is : 

> Some phones that support 4K YouTube seem not to support 4K here.

I thinks encoding YouTube are different. We should reproduce with develop branch, @scanlime ?

**Comment by scanlime** [comment]
Re retesting... 

Diode.zone is running a branch which is currently very close to current develop. The changes relative to develop shouldn't affect this, but if anyone wants the exact code it's here: https://github.com/scanlime/PeerTube/tree/diode.zone

I'm still not seeing 4K videos play back smoothly. Of course this will depend on computer speed, but I just tested on Google Chrome on a fast Xeon desktop, and this short 4K video plays nearly smoothly but still stops once or so per playback. I'll look for some longer 4K footage I can upload as a test.

https://diode.zone/videos/watch/6f111ebd-d595-4b01-97b1-903d9a694665

**Comment by scanlime** [comment]
I can no longer reproduce this after running the optimize-old-videos script, guess it was just a bitrate issue after all!
